# Generated by Django 5.0.6 on 2024-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField()),
                ('ph_number', models.IntegerField()),
                ('mail_id', models.CharField()),
                ('occup', models.CharField()),
            ],
        ),
    ]
